version: "3.9"
services:
  attacker:
    image: python-backdoor-attacker:0.0.1
    build:
      context: attacker
      dockerfile: ./Dockerfile.attacker
    networks:
      internal-network:
        ipv4_address: "10.0.45.15"

  target:
    image: python-backdoor-target:0.0.1
    build:
      context: target
      dockerfile: ./Dockerfile.target
    networks:
      internal-network:
        ipv4_address: "10.0.45.16"

networks:
  internal-network:
    ipam:
      driver: default
      config:
        - subnet: "10.0.45.0/24"
